[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
gtfs.workspace = true
serde.workspace = true
serde_json.workspace = true
deutsche_bahn.workspace = true

tokio.workspace = true
